
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer ut_create_buffer
#define yy_delete_buffer ut_delete_buffer
#define yy_flex_debug ut_flex_debug
#define yy_init_buffer ut_init_buffer
#define yy_flush_buffer ut_flush_buffer
#define yy_load_buffer_state ut_load_buffer_state
#define yy_switch_to_buffer ut_switch_to_buffer
#define yyin utin
#define yyleng utleng
#define yylex utlex
#define yylineno utlineno
#define yyout utout
#define yyrestart utrestart
#define yytext uttext
#define yywrap utwrap
#define yyalloc utalloc
#define yyrealloc utrealloc
#define yyfree utfree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE utrestart(utin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern yy_size_t utleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *utin, *utout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up uttext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up uttext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via utrestart()), so that the user can continue scanning by
	 * just pointing utin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when uttext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t utleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow utwrap()'s to do buffer switches
 * instead of setting up a fresh utin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void utrestart (FILE *input_file  );
void ut_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ut_create_buffer (FILE *file,int size  );
void ut_delete_buffer (YY_BUFFER_STATE b  );
void ut_flush_buffer (YY_BUFFER_STATE b  );
void utpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void utpop_buffer_state (void );

static void utensure_buffer_stack (void );
static void ut_load_buffer_state (void );
static void ut_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ut_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ut_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ut_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ut_scan_bytes (yyconst char *bytes,yy_size_t len  );

/* %endif */

void *utalloc (yy_size_t  );
void *utrealloc (void *,yy_size_t  );
void utfree (void *  );

#define yy_new_buffer ut_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        utensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ut_create_buffer(utin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        utensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ut_create_buffer(utin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] uttext/utin/utout/yy_state_type/utlineno etc. def's & init go here */
/* Begin user sect3 */

#define utwrap(n) 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *utin = (FILE *) 0, *utout = (FILE *) 0;

typedef int yy_state_type;

extern int utlineno;

int utlineno = 1;

extern char *uttext;
#define yytext_ptr uttext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up uttext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle uttext and utleng for yymore() goes here \ */\
	utleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to uttext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[276] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       22,   20,    4,   21,   19,    4,   20,    4,    4,    3,
       15,    2,   19,   19,   19,   19,   19,   19,   20,   19,
       20,   20,   20,   20,   20,   20,    4,    4,   15,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
        8,   20,   10,   10,   10,   20,   13,   20,    4,    3,
        2,    0,    0,    0,    0,    0,    0,    0,   15,   14,
        3,   14,    0,    2,    0,   19,   19,    0,    0,    0,
        0,   19,   19,   19,   19,    0,    5,   19,   19,   19,
       19,   19,    6,    4,    0,    0,   15,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    8,    8,
        0,    8,    8,    8,    8,   10,   10,   10,   10,   10,
        0,   10,   10,   12,   13,    0,    0,   14,    0,   14,
       19,    0,   19,    3,    1,   19,    0,    0,    0,    0,
        0,    0,    0,    0,    6,   19,    0,    0,    1,    0,
        6,    0,    0,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   10,   10,   10,    9,
        9,   10,   10,   10,   10,   11,    0,   14,   19,    2,
        1,   19,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    7,    0,    7,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   10,   10,    9,    0,
       18,   16,   17,    0,    0,    7,    7,    7,   15,    8,
        8,    8,    8,    8,    8,    8,   15,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,   10,    9,
        9,    9,   18,    0,   16,    0,   17,    0,    6,    8,
        8,    8,   15,    8,    8,    8,    8,    8,    8,    9,
       18,   16,   17,    9,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    6,    7,
        1,    8,    9,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   17,   18,   19,   19,   19,   20,    1,    1,
        1,    1,    1,   21,   22,   23,   24,   23,   25,   26,
       23,   23,   27,   23,   23,   23,   28,   29,   30,   31,
       23,   32,   33,   34,   23,   23,   23,   23,   23,   23,
        1,    1,    1,   35,   23,    1,   22,   36,   24,   23,

       25,   26,   37,   23,   27,   23,   23,   38,   28,   39,
       40,   31,   23,   32,   33,   41,   23,   23,   23,   23,
       23,   23,    1,    1,    1,    1,    1,   42,   43,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       44,   45,   45,   45,   45,   45,   45,   45,   45,   46,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   47,   45,   45,   48,   45,   49,   50,   51,
       52,   51,   53,   54,   55,   56,   57,   58,   58,   58,
       58,    1,    1,   59,   60,    1,    1,    1,    1,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   62,   62,   63,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    3,    2,    2,    2,    2,    2,    2,
        2,    2,    3,    2,    2,    2,    2,    2,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[281] =
    {   0,
        0,    0,   62,  124,  186,    0,  216,  227,  245,    0,
     1097, 1234,   80, 1234, 1234, 1088,  150,  159,  101, 1093,
      195, 1092,  296, 1067,   59,   41,   43,   60,  272,  145,
      246,    0,   45,    0, 1049,  325,  332, 1234,  347, 1065,
     1058, 1061, 1060, 1056,   68,   98, 1030,   97,  356,  363,
      381,  371,  403,  411,  430,  420,  438,   76,  457, 1054,
     1052, 1027, 1020, 1026, 1025, 1019,  457,  478,  487,  500,
     1031,  513,  526, 1030, 1005,  988,  181,  146,    0,  105,
        0,  239,   64,  977,  244,  533,  540,  458,  461,  558,
      153,  974,  158, 1234,  175,  543,  553,   69,  114,  947,

      914,  210,  184,  270,  295,  866,  525,  128,    0,  873,
      589,  607,  640,  237, 1234,  662,  670,  853,  689,  697,
      597,  716,  723,  620,  730,  630,  742,  749,  679,  762,
      249,  263,  277,  438,  459,  328,  400,  409,  401,  410,
      402,  475,  431,  795,  603,  604,  767,  744,  751,  649,
      351,  461,  705,  780,  781,  814,  847,  495,    0,  880,
      508,  520,    0,  548,    0,    0,  785,  902,  920,  910,
      650,  930,  940,  658,  572,  792,  804,  827,  274,  771,
      666,  602,  629,  594,  752,  550,  824,  512,  799,  821,
      468,  467,  457,  460,  870, 1234,  958,  991,  713,    0,

     1024,  756,  687,    0,  821,    0,    0,    0,    0,    0,
      772,    0,    0,    0,    0,    0,  948, 1046,  399,  971,
      857,  872,  950,  967,  892, 1053, 1010,  214, 1063, 1087,
      865,  968, 1120,  887,  775,    0, 1100,    0,    0,    0,
        0,    0,  799,    0,  981,    0,    0,    0, 1142, 1151,
     1034, 1073,  391,  366,  351,  329,  315,  282,  954,    0,
     1169,  983, 1182, 1014,    0,    0,  985,  255,    0, 1200,
      221,  178,  150, 1207, 1234, 1226,  129, 1228,  107, 1230
    } ;

static yyconst flex_int16_t yy_def[281] =
    {   0,
      275,    1,  276,  276,  276,    5,    5,    5,    1,    9,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,   23,   23,   23,   23,   23,  275,   23,
      275,  277,  277,  278,  278,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,   23,   23,   23,  275,  279,  279,
      280,   23,   23,   23,   23,  275,  275,   23,   23,   23,
       23,   23,  275,  275,  277,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,   51,  275,
      275,  275,  275,  113,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
       23,  279,   23,   23,   23,   23,  275,  275,  275,  275,
      275,  275,  275,  275,   23,   23,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  157,  158,  275,
      160,  158,  158,  158,  160,  161,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,   23,   23,
      275,   23,  275,  275,  275,  275,  275,  275,  275,  275,
      280,  275,  275,  275,  275,  275,  275,  275,  198,  199,

      275,  201,  199,  199,  199,  201,  202,  199,  201,  202,
      199,  199,  205,  201,  202,  198,  275,  275,  275,  275,
      275,  275,  275,  279,  275,  275,  275,  275,  275,  275,
      230,  199,  275,  233,  231,  231,  275,  233,  234,  232,
      233,  234,  231,  231,  205,  233,  234,  230,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,   23,  231,
      275,  261,  275,  231,  231,  261,  261,  264,  264,  275,
      275,  275,  275,  275,    0,  275,  275,  275,  275,  275
    } ;

static yyconst flex_int16_t yy_nxt[1298] =
    {   0,
       12,   13,   14,   15,   15,   15,   12,   16,   17,   18,
       19,   20,   21,   21,   21,   21,   21,   21,   21,   12,
       22,   23,   24,   24,   24,   25,   24,   24,   24,   24,
       26,   27,   28,   24,   29,   24,   24,   30,   24,   24,
       24,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   31,   32,
       33,   34,   35,   13,   14,   83,   76,   84,   76,   16,
       36,   37,   38,   20,   39,   39,   39,   39,   39,   39,
       39,   59,   22,   40,   76,   76,   85,   41,   92,   76,
       82,   60,   42,   43,   44,  134,   29,   92,  108,   45,

       61,   62,  147,  103,  104,   63,  105,  106,   76,  147,
       64,   65,   66,   70,   70,   70,   70,   70,   70,   70,
       46,   92,   92,   92,   47,   13,   14,   92,   65,  108,
       92,   16,   36,   37,   38,   20,   39,   39,   39,   39,
       39,   39,   39,  148,   22,   40,   93,   93,   76,   41,
       94,  257,   93,  148,   42,   43,   44,   76,   29,   65,
       68,   45,   69,   69,   69,   69,   69,   69,   69,   68,
       76,   69,   69,   69,   69,   69,   69,   69,   76,  255,
       88,   89,   46,   90,   91,  137,   47,   48,   14,   89,
      138,   76,   76,   76,   49,   49,   50,   76,   51,   51,

       51,   51,   51,   51,   51,   72,   76,   69,   69,   69,
       69,   69,   69,   69,  131,  194,  143,   43,   92,   73,
      144,  131,  253,   45,   52,   52,   12,   92,   53,   53,
       54,   55,   55,   55,   55,   52,   52,   12,  150,   53,
       53,   54,   55,   55,   55,   55,   48,  196,  150,  164,
      165,  166,   12,   56,   56,   12,   12,   57,   57,   57,
       57,   57,   57,   57,   76,   12,   24,   69,  133,   76,
       24,  139,  136,  179,   76,   24,  140,   24,  133,   12,
       86,   86,  136,  273,   87,   87,   87,   87,   87,   87,
       87,   92,   92,   92,   93,   93,  141,   92,   94,   76,

       93,  142,   76,   58,  180,  180,   76,   34,   75,   75,
       75,   75,   75,   75,   75,   76,  257,   76,   76,   76,
       76,   77,   76,   76,   76,   76,   76,   76,   76,   76,
      272,   76,   76,   76,   76,   76,   76,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,  182,  255,   76,   78,   79,   80,   81,   81,   97,
       97,   97,   97,   97,   97,   97,   68,  271,  109,  109,
      109,  109,  109,  109,  109,   70,   70,   70,   70,   70,
       70,   70,  110,  116,  116,  117,  117,  117,  117,  117,
      111,   72,  253,  112,  113,  114,  114,  114,  114,  114,

      219,  137,  139,  141,  118,   73,  138,  140,  142,  143,
      183,  185,  118,  144,  115,  119,  119,  119,  119,  119,
      120,  120,  121,  119,  119,  119,  119,  122,  123,  123,
      121,  118,  124,  124,  124,  124,  124,  124,  124,   71,
      184,  186,  122,  122,  122,  122,  122,  123,  123,  121,
      125,  125,  125,  125,  125,  125,  125,  126,   59,  137,
      181,  194,  139,   76,  138,   86,   86,  140,   60,   87,
       87,   87,   87,   87,   87,   87,  187,   61,   62,   93,
       93,   61,   63,   76,   76,   93,   76,   64,   65,   66,
       70,   70,   70,   70,   70,   70,   70,   72,   61,   69,

       69,   69,   69,   69,   69,   69,  188,  205,  206,  207,
      224,   73,   70,   70,   70,   70,   70,   70,   70,  143,
      213,  214,  215,  144,  127,  128,  128,  128,  128,  128,
      128,  128,  213,  214,  129,  129,  223,  127,  130,  130,
      130,  130,  130,  130,  130,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,  141,
      197,  216,  204,  204,  142,   97,   97,   97,   97,   97,
       97,   97,  151,  118,  222,  151,  151,  151,  151,  151,
      152,  152,  217,   76,   92,   92,   92,   92,   92,   92,
      145,   92,   92,  145,  145,  145,  145,  145,  146,  146,

       92,  153,  154,  155,  155,  155,  155,  155,  110,  170,
      170,  170,  170,  170,  171,  171,  111,   72,  221,  156,
      157,  158,  158,  158,  158,  158,  180,   76,   76,   76,
      183,   73,  124,  124,  124,  124,  124,  124,  124,  126,
      115,  110,  176,  176,  176,  176,  176,  176,  176,  111,
       72,  219,  159,  160,  161,  162,  163,  163,  163,  118,
      184,  190,  190,  118,   73,  191,  191,  181,  217,  220,
      175,  118,  193,  115,  119,  119,  119,  119,  119,  120,
      120,  121,  122,  122,  122,  122,  122,  123,  123,  121,
      118,  130,  130,  130,  130,  130,  130,  130,  118,  245,

      246,  167,  167,  167,  167,  167,  168,  169,  121,  167,
      167,  167,  167,  167,  168,  169,  121,  118,  155,  155,
      155,  155,  155,  155,  118,  237,  238,  239,  172,  172,
      172,  172,  172,  168,  169,  173,  173,  173,  173,  173,
      174,  175,  125,  125,  125,  125,  125,  125,  125,  126,
      177,  177,  181,  185,  178,  178,  178,  178,  178,  178,
      178,  128,  128,  128,  128,  128,  128,  128,  245,  246,
      247,   61,   74,  127,  130,  130,  130,  130,  130,  130,
      130,  194,  194,  186,  245,  246,  118,  268,  269,  195,
      195,  192,  155,  155,  155,  217,   76,  172,  172,  172,

      172,  172,  168,  169,  176,  176,  176,  176,  176,  176,
      176,  268,  269,  196,  196,  110,  178,  178,  178,  178,
      178,  178,  178,  111,   72,  187,  197,  198,  199,  199,
      199,  199,  199,  229,  248,  236,  236,  189,   73,  178,
      178,  178,  178,  178,  178,  178,  151,  115,  110,  151,
      151,  151,  151,  151,  118,  188,  111,   72,  253,  200,
      201,  202,  203,  204,  204,  204,   76,   76,   76,   93,
       93,   73,   76,  255,  110,   93,  254,  263,  264,  264,
      115,  110,  225,  226,  226,  227,  228,  228,  228,  111,
       72,  256,  208,  209,  210,  211,  212,  212,  212,  268,

      269,  269,  104,  118,   73,  228,  228,  228,  228,  228,
      228,  219,  217,  115,  218,  173,  173,  173,  173,  174,
      175,  118,  171,  171,  171,  171,  171,  171,  171,  220,
      217,  118,  173,  173,  173,  173,  173,  174,  175,  149,
      217,  118,  173,  173,  173,  173,  173,  174,  175,  118,
      217,  257,  175,  175,  175,  175,  175,  175,  175,  110,
      249,  249,  249,  249,  249,  249,  249,  111,   72,  258,
      229,  230,  231,  231,  231,  231,  231,  275,   60,   76,
      263,  239,   73,  250,  250,  250,  250,  250,  251,  252,
      275,  115,  110,   69,  236,   69,   69,   69,   69,   76,

      111,   72,  135,  232,  233,  234,  235,  236,  236,  236,
       76,  194,  190,   76,  259,   73,  191,  259,  259,  259,
      259,  259,  228,  228,  115,  110,  262,  262,  262,  262,
       76,   74,   71,  111,   72,  219,  240,  241,  242,  243,
      244,  244,  244,  196,  270,  102,  252,  118,   73,  101,
      100,   99,   98,   74,  194,   71,  217,  115,  175,  175,
      175,  175,  175,  175,  175,  228,  228,  228,  228,  228,
      228,  228,  107,   72,  219,   69,  231,  231,  231,  231,
      231,  231,  102,  270,  101,  100,  196,   73,  110,   99,
       98,   96,   76,   74,   71,   67,  275,   72,  275,  260,

      239,  239,  261,  262,  262,  262,  275,  275,  275,  275,
       72,   73,   69,  236,  236,  236,  236,  236,  236,  275,
      115,  110,  275,  275,   73,  275,  275,  275,  275,  275,
       72,  275,  265,  247,  247,  266,  267,  267,  267,  275,
      275,  275,  275,  118,   73,  275,  275,  275,  275,  275,
      275,  275,  219,  115,  249,  249,  249,  249,  249,  249,
      249,  270,  275,  252,  252,  252,  252,  252,  252,  252,
      110,  275,  275,  275,  275,  275,  275,  275,  275,   72,
      275,  262,  262,   69,   69,   69,   69,   69,  275,  275,
      275,  275,   72,   73,   69,  262,  262,  262,  262,  262,

      262,  219,  115,  275,  275,  275,   73,  275,  219,  275,
      275,  275,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,   12,   12,   12,   95,
       95,  132,  132,   11,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275

    } ;

static yyconst flex_int16_t yy_chk[1298] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,   26,   26,   27,   27,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,   13,    3,    3,   25,   28,   28,    3,   33,   83,
       25,   13,    3,    3,    3,   83,    3,   33,   48,    3,

       13,   13,   98,   45,   45,   13,   45,   45,  279,   98,
       13,   13,   13,   19,   19,   19,   19,   19,   19,   19,
        3,   58,   58,   58,    3,    4,    4,   58,   48,  108,
      277,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,   99,    4,    4,   46,   46,   80,    4,
       46,  273,   46,   99,    4,    4,    4,   80,    4,  108,
       17,    4,   17,   17,   17,   17,   17,   17,   17,   18,
       30,   18,   18,   18,   18,   18,   18,   18,   91,  272,
       30,   30,    4,   30,   30,  103,    4,    5,    5,   91,
      103,   78,   78,   78,    5,    5,    5,   78,    5,    5,

        5,    5,    5,    5,    5,   21,   77,   21,   21,   21,
       21,   21,   21,   21,   77,  228,   93,    5,   95,   21,
       93,   77,  271,    5,    7,    7,    7,   95,    7,    7,
        7,    7,    7,    7,    7,    8,    8,    8,  102,    8,
        8,    8,    8,    8,    8,    8,    9,  228,  102,  114,
      114,  114,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   82,    9,    9,  268,   82,   85,
        9,  104,   85,  131,  131,    9,  104,    9,   82,    9,
       29,   29,   85,  258,   29,   29,   29,   29,   29,   29,
       29,   31,   31,   31,   31,   31,  105,   31,   31,  179,

       31,  105,  133,    9,  133,  179,  132,    9,   23,   23,
       23,   23,   23,   23,   23,  132,  257,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
      256,   23,   23,   23,   23,   23,   23,   36,   36,   36,
       36,   36,   36,   36,   37,   37,   37,   37,   37,   37,
       37,  136,  255,  136,   23,   23,   23,   23,   23,   39,
       39,   39,   39,   39,   39,   39,   49,  254,   49,   49,
       49,   49,   49,   49,   49,   50,   50,   50,   50,   50,
       50,   50,   51,   52,   52,   52,   52,   52,   52,   52,
       51,   51,  253,   51,   51,   51,   51,   51,   51,   51,

      219,  137,  139,  141,   53,   51,  137,  139,  141,  151,
      138,  140,   54,  151,   51,   53,   53,   53,   53,   53,
       53,   53,   53,   54,   54,   54,   54,   54,   54,   54,
       54,   55,   56,   56,   56,   56,   56,   56,   56,  134,
      138,  140,   55,   55,   55,   55,   55,   55,   55,   55,
       57,   57,   57,   57,   57,   57,   57,   57,   59,   88,
      135,  194,   89,  134,   88,   67,   67,   89,   59,   67,
       67,   67,   67,   67,   67,   67,  142,   59,   59,  143,
      143,  193,   59,   88,  135,  143,   89,   59,   59,   59,
       68,   68,   68,   68,   68,   68,   68,   69,  192,   69,

       69,   69,   69,   69,   69,   69,  142,  158,  158,  158,
      191,   69,   70,   70,   70,   70,   70,   70,   70,  152,
      161,  161,  161,  152,   70,   72,   72,   72,   72,   72,
       72,   72,  162,  162,   73,   73,  188,   72,   73,   73,
       73,   73,   73,   73,   73,   86,   86,   86,   86,   86,
       86,   86,   87,   87,   87,   87,   87,   87,   87,   90,
      164,  164,  164,  164,   90,   97,   97,   97,   97,   97,
       97,   97,  107,  175,  186,  107,  107,  107,  107,  107,
      107,  107,  175,   90,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,

       96,  111,  111,  111,  111,  111,  111,  111,  112,  121,
      121,  121,  121,  121,  121,  121,  112,  112,  184,  112,
      112,  112,  112,  112,  112,  112,  182,  182,  145,  146,
      183,  112,  124,  124,  124,  124,  124,  124,  124,  124,
      112,  113,  126,  126,  126,  126,  126,  126,  126,  113,
      113,  171,  113,  113,  113,  113,  113,  113,  113,  174,
      183,  145,  146,  116,  113,  145,  146,  181,  174,  171,
      174,  117,  150,  113,  116,  116,  116,  116,  116,  116,
      116,  116,  117,  117,  117,  117,  117,  117,  117,  117,
      119,  129,  129,  129,  129,  129,  129,  129,  120,  203,

      203,  119,  119,  119,  119,  119,  119,  119,  119,  120,
      120,  120,  120,  120,  120,  120,  120,  122,  153,  153,
      153,  153,  153,  153,  123,  199,  199,  199,  122,  122,
      122,  122,  122,  122,  122,  123,  123,  123,  123,  123,
      123,  123,  125,  125,  125,  125,  125,  125,  125,  125,
      127,  127,  149,  185,  127,  127,  127,  127,  127,  127,
      127,  128,  128,  128,  128,  128,  128,  128,  202,  202,
      202,  148,  180,  128,  130,  130,  130,  130,  130,  130,
      130,  154,  155,  185,  211,  211,  167,  235,  235,  154,
      155,  147,  154,  154,  154,  167,  180,  167,  167,  167,

      167,  167,  167,  167,  176,  176,  176,  176,  176,  176,
      176,  243,  243,  154,  155,  156,  177,  177,  177,  177,
      177,  177,  177,  156,  156,  187,  156,  156,  156,  156,
      156,  156,  156,  205,  205,  205,  205,  144,  156,  178,
      178,  178,  178,  178,  178,  178,  189,  156,  157,  189,
      189,  189,  189,  189,  118,  187,  157,  157,  221,  157,
      157,  157,  157,  157,  157,  157,  190,  190,  190,  190,
      190,  157,  190,  222,  110,  190,  221,  231,  231,  231,
      157,  160,  195,  195,  195,  195,  195,  195,  195,  160,
      160,  222,  160,  160,  160,  160,  160,  160,  160,  234,

      234,  234,  106,  168,  160,  225,  225,  225,  225,  225,
      225,  170,  168,  160,  168,  168,  168,  168,  168,  168,
      168,  169,  170,  170,  170,  170,  170,  170,  170,  170,
      169,  172,  169,  169,  169,  169,  169,  169,  169,  101,
      172,  173,  172,  172,  172,  172,  172,  172,  172,  217,
      173,  223,  173,  173,  173,  173,  173,  173,  173,  197,
      217,  217,  217,  217,  217,  217,  217,  197,  197,  223,
      197,  197,  197,  197,  197,  197,  197,  232,  100,  259,
      232,  232,  197,  220,  220,  220,  220,  220,  220,  220,
      245,  197,  198,  245,  245,  262,  262,  267,  267,   92,

      198,  198,   84,  198,  198,  198,  198,  198,  198,  198,
      224,  227,  259,   76,  224,  198,  259,  224,  224,  224,
      224,  224,  227,  227,  198,  201,  264,  264,  264,  264,
       75,   74,   71,  201,  201,  251,  201,  201,  201,  201,
      201,  201,  201,  227,  251,   66,  251,  218,  201,   65,
       64,   63,   62,   61,  226,   60,  218,  201,  218,  218,
      218,  218,  218,  218,  218,  226,  226,  226,  226,  226,
      226,  226,   47,  229,  252,  229,  229,  229,  229,  229,
      229,  229,   44,  252,   43,   42,  226,  229,  230,   41,
       40,   35,   24,   22,   20,   16,   11,  230,    0,  230,

      230,  230,  230,  230,  230,  230,    0,    0,    0,    0,
      237,  230,  237,  237,  237,  237,  237,  237,  237,    0,
      230,  233,    0,    0,  237,    0,    0,    0,    0,    0,
      233,    0,  233,  233,  233,  233,  233,  233,  233,    0,
        0,    0,    0,  249,  233,    0,    0,    0,    0,    0,
        0,    0,  250,  233,  249,  249,  249,  249,  249,  249,
      249,  250,    0,  250,  250,  250,  250,  250,  250,  250,
      261,    0,    0,    0,    0,    0,    0,    0,    0,  261,
        0,  261,  261,  261,  261,  261,  261,  261,    0,    0,
        0,    0,  263,  261,  263,  263,  263,  263,  263,  263,

      263,  270,  261,    0,    0,    0,  263,    0,  274,    0,
        0,    0,  270,  270,  270,  270,  270,  270,  270,  274,
      274,  274,  274,  274,  274,  274,  276,  276,  276,  278,
      278,  280,  280,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ut_flex_debug;
int ut_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[21] =
    {   0,
      151,  156,  161,  166,  171,  186,  243,  248,  259,  265,
      271,  277,  287,  297,  302,  320,  325,  330,  335,  342
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *uttext;
#line 1 "scanner.l"
/*
 * Copyright 2014 University Corporation for Atmospheric Research
 *
 * This file is part of the UDUNITS-2 package.  See the file COPYRIGHT
 * in the top-level source-directory of the package for copying and
 * redistribution conditions.
 */
/*
 * lex(1) specification for tokens for the Unidata units package, UDUNITS2.
 */
#line 15 "scanner.l"

#include <ctype.h>
#include <errno.h>
#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/**
 * Decodes a date.
 *
 * @param[in]  text     The text specifying the date to be decoded.
 * @param[in]  format   The format to use for decoding. The order is year (int),
 *                      month (int), and day (int).
 * @param[out] date     The date corresponding to the input.
 * @retval     DATE     Success
 * @retval     ERR      Error
 */
static double decodeDate(
    const char* const   text,
    const char* const   format,
    double* const       date)
{
    int		year;
    int		month = 1;
    int		day = 1;

    (void)sscanf(text, format, &year, &month, &day);
    *date = ut_encode_date(year, month, day);
    return DATE;
}

/**
 * Decodes a clock-time.
 *
 * @param[in] text      The text specifying the clock-time to be decoded.
 * @param[in] format    The format to use for decoding. The order is hour (int),
 *                      minute (int), and second (double).
 * @return              The clock-time corresponding to the input.
 */
static double decodeClock(
    const char* const   text,
    const char* const   format)
{
    int         hour = 0;
    int         minute = 0;
    double      second = 0;

    (void)sscanf(text, format, &hour, &minute, &second);
    if (hour < 0) {
        minute = -minute;
        second = -second;
    }
    return ut_encode_clock(hour, minute, second);
}

/**
 * Decodes a real value.
 *
 * @param[in]  text     Text to be decoded.
 * @param[out] value    Decoded value.
 * @retval     REAL     Success.
 * @retval     ERR      Failure.
 */
static int decodeReal(
    const char* const text,
    double* const     value)
{
    errno = 0;
    *value = atof(text);

    if (errno == 0)
        return REAL;

    ut_handle_error_message("Invalid real: \"%s\"", text);
    return ERR;
}


#line 1029 "<stdout>"

#define INITIAL 0
#define ID_SEEN 1
#define SHIFT_SEEN 2
#define DATE_SEEN 3
#define CLOCK_SEEN 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#ifndef _MSC_VER
#include <unistd.h>
#endif
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int utlex_destroy (void );

int utget_debug (void );

void utset_debug (int debug_flag  );

YY_EXTRA_TYPE utget_extra (void );

void utset_extra (YY_EXTRA_TYPE user_defined  );

FILE *utget_in (void );

void utset_in  (FILE * in_str  );

FILE *utget_out (void );

void utset_out  (FILE * out_str  );

yy_size_t utget_leng (void );

char *utget_text (void );

int utget_lineno (void );

void utset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int utwrap (void );
#else
extern int utwrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( uttext, utleng, 1, utout )
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( utin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( utin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, utin))==0 && ferror(utin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(utin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int utlex (void);

#define YY_DECL int utlex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after uttext and utleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 145 "scanner.l"

    if (_restartScanner) {
	BEGIN INITIAL;
	_restartScanner = 0;
    }

#line 1282 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! utin )
/* %if-c-only */
			utin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! utout )
/* %if-c-only */
			utout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			utensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ut_create_buffer(utin,YY_BUF_SIZE );
		}

		ut_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of uttext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 276 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1234 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for utlineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( ut_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 21 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], uttext );
			else if ( yy_act == 21 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         uttext );
			else if ( yy_act == 22 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 151 "scanner.l"
{
    BEGIN INITIAL;
    return SHIFT;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 156 "scanner.l"
{
    BEGIN SHIFT_SEEN;
    return SHIFT;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 161 "scanner.l"
{
    BEGIN INITIAL;
    return DIVIDE;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 166 "scanner.l"
{
    BEGIN INITIAL;
    return MULTIPLY;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 171 "scanner.l"
{
    int		status;

    if (sscanf(uttext, "%*[*^]%ld", &yylval.ival) != 1) {
        ut_handle_error_message("Invalid integer\n", stderr);

	status	= ERR;
    }
    else {
	status	= EXPONENT;
    }

    return status;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 186 "scanner.l"
{
    int		status = EXPONENT;
    int		exponent = 0;
    int		sign = 1;
    char*	cp = uttext;

    if (strncmp(cp, "\xe2\x81\xba", 3) == 0) {
	cp += 3;
    }
    else if (strncmp(cp, "\xe2\x81\xbb", 3) == 0) {
	sign = -1;
	cp += 3;
    }

    while (cp < uttext + utleng) {
	int	j;
	static struct {
	    const char*	string;
	    const int	len;
	} utf8_exponents[] = {
	    {"\xe2\x81\xb0", 3},        /* 0 */
	    {"\xc2\xb9",     2},        /* 1 */
	    {"\xc2\xb2",     2},        /* 2 */
	    {"\xc2\xb3",     2},        /* 3 */
	    {"\xe2\x81\xb4", 3},        /* 4 */
	    {"\xe2\x81\xb5", 3},        /* 5 */
	    {"\xe2\x81\xb6", 3},        /* 6 */
	    {"\xe2\x81\xb7", 3},        /* 7 */
	    {"\xe2\x81\xb8", 3},        /* 8 */
	    {"\xe2\x81\xb9", 3},        /* 9 */
	};

	exponent *= 10;

	for (j = 0; j < 10; j++) {
	    int	len = utf8_exponents[j].len;

	    if (strncmp(cp, utf8_exponents[j].string, len) == 0) {
		exponent += j;
		cp += len;
		break;
	    }
	}

	if (j >= 10) {
	    status = ERR;
	    break;
	}
    }

    if (status == EXPONENT)
	yylval.ival = sign * exponent;

    BEGIN INITIAL;
    return status;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 243 "scanner.l"
{
    BEGIN DATE_SEEN;
    return decodeDate((char*)uttext, "%d-%d-%d", &yylval.rval);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 248 "scanner.l"
{
    if (_isTime) {
        BEGIN DATE_SEEN;
        return decodeDate((char*)uttext, "%4d%2d%2d", &yylval.rval);
    }
    else {
        BEGIN INITIAL;
        return decodeReal((char*)uttext, &yylval.rval);
    }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 259 "scanner.l"
{
    yylval.rval = decodeClock((char*)uttext, "%d:%d:%lf");
    BEGIN CLOCK_SEEN;
    return CLOCK;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 265 "scanner.l"
{
    yylval.rval = decodeClock((char*)uttext, "%2d%2d%lf");
    BEGIN CLOCK_SEEN;
    return CLOCK;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 271 "scanner.l"
{
    yylval.rval	= decodeClock((char*)uttext, "%d:%d");
    BEGIN INITIAL;
    return CLOCK;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 277 "scanner.l"
{
    yylval.rval	= (utleng <= 3)
                        ? decodeClock((char*)uttext, "%d")
                        : (utleng == 4)
                            ? decodeClock((char*)uttext, "%2d%d")
                            : decodeClock((char*)uttext, "%3d%d");
    BEGIN INITIAL;
    return CLOCK;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 287 "scanner.l"
{
    yylval.rval	= (utleng <= 2)
                        ? decodeClock((char*)uttext, "%d")
                        : (utleng == 3)
                            ? decodeClock((char*)uttext, "%1d%d")
                            : decodeClock((char*)uttext, "%2d%d");
    BEGIN INITIAL;
    return CLOCK;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 297 "scanner.l"
{
    BEGIN INITIAL;
    return decodeReal((char*)uttext, &yylval.rval);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 302 "scanner.l"
{
    int		status;

    errno	= 0;
    yylval.ival = atol((char*)uttext);

    if (errno == 0) {
	status	= INT;
    } else {
        ut_handle_error_message("Invalid integer\n", stderr);

	status	= ERR;
    }

    BEGIN INITIAL;
    return status;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 320 "scanner.l"
{
    yylval.rval = 10;
    return LOGREF;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 325 "scanner.l"
{
    yylval.rval = M_E;
    return LOGREF;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 330 "scanner.l"
{
    yylval.rval = 2;
    return LOGREF;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 335 "scanner.l"
{
    yylval.id = strdup((char*)uttext);

    BEGIN ID_SEEN;
    return ID;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 342 "scanner.l"
{
    BEGIN INITIAL;
    return uttext[0];
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 347 "scanner.l"
ECHO;
	YY_BREAK
#line 1657 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ID_SEEN):
case YY_STATE_EOF(SHIFT_SEEN):
case YY_STATE_EOF(DATE_SEEN):
case YY_STATE_EOF(CLOCK_SEEN):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed utin at a new source and called
			 * utlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = utin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( utwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * uttext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of utlex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					utrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			utrestart(utin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) utrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 276 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 276 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 275);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up uttext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update utlineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					utrestart(utin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( utwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve uttext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and utlineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void utrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        utensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ut_create_buffer(utin,YY_BUF_SIZE );
	}

	ut_init_buffer(YY_CURRENT_BUFFER,input_file );
	ut_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void ut_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		utpop_buffer_state();
	 *		utpush_buffer_state(new_buffer);
     */
	utensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ut_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (utwrap()) processing, but the only time this flag
	 * is looked at is after utwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void ut_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	utin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE ut_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) utalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ut_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) utalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ut_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ut_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ut_create_buffer()
 * 
 */
/* %if-c-only */
    void ut_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		utfree((void *) b->yy_ch_buf  );

	utfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a utrestart() or at EOF.
 */
/* %if-c-only */
    static void ut_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	ut_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ut_init_buffer was _probably_
     * called from utrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void ut_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ut_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void utpush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	utensure_buffer_stack();

	/* This block is copied from ut_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ut_switch_to_buffer. */
	ut_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void utpop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ut_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ut_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void utensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)utalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in utensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)utrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in utensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ut_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) utalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ut_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ut_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to utlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ut_scan_bytes() instead.
 */
YY_BUFFER_STATE ut_scan_string (yyconst char * yystr )
{
    
	return ut_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to utlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ut_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) utalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ut_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ut_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ut_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up uttext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		uttext[utleng] = (yy_hold_char); \
		(yy_c_buf_p) = uttext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		utleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int utget_lineno  (void)
{
        
    return utlineno;
}

/** Get the input stream.
 * 
 */
FILE *utget_in  (void)
{
        return utin;
}

/** Get the output stream.
 * 
 */
FILE *utget_out  (void)
{
        return utout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t utget_leng  (void)
{
        return utleng;
}

/** Get the current token.
 * 
 */

char *utget_text  (void)
{
        return uttext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void utset_lineno (int  line_number )
{
    
    utlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ut_switch_to_buffer
 */
void utset_in (FILE *  in_str )
{
        utin = in_str ;
}

void utset_out (FILE *  out_str )
{
        utout = out_str ;
}

int utget_debug  (void)
{
        return ut_flex_debug;
}

void utset_debug (int  bdebug )
{
        ut_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from utlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    utin = stdin;
    utout = stdout;
#else
    utin = (FILE *) 0;
    utout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * utlex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* utlex_destroy is for both reentrant and non-reentrant scanners. */
int utlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ut_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		utpop_buffer_state();
	}

	/* Destroy the stack itself. */
	utfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * utlex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *utalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *utrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void utfree (void * ptr )
{
	free( (char *) ptr );	/* see utrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 347 "scanner.l"



